name: CI
on: [push, pull_request]
jobs:
  test:
    name: Test with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ['10', '12', '14', '15']
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: npm install-test
        env:
          CI: true
