name: CI
on: [push, workflow_dispatch]
jobs:
  test:
    name: Test with Node.js v${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ["18", "20", "21"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: npm install and test
        run: npm install-test
